name: 'Retry Command'
description: 'Retry a simple command'
inputs:
  command:
    description: 'Command to run'
    required: true
  max_retries:
    description: 'Maximum number of attends to retry the command. Default 3'
    default: 3
    required: false
  retry_wait:
    description: 'Number of seconds to wait between retry attends. Default 5 seconds'
    default: 5
    required: false
runs:
  using: "composite"
  steps:
    - name: Run command
      run: |
          retry() {
            local retries=$1
            local retryWait=$2
            local command="$3"
            local currentRetry="${4:-1}"
          
            # Run the command and keep the exit code
            echo "::notice ::Running command '$command'"

            # Disable set -e
            set +e
            
            $command          
            local exit_code=$?

            # Restore initial options
            set -e
          
            # If the exit code is a non-zero value (i.e. command failed), and we have not
            # reached the maximum number of retries, run the command again
            if [[ $exit_code -ne 0 && $retries -gt 0 ]]; then
              echo "::warning ::Attempt $(($currentRetry)) failed. Exit code: $exit_code"
              
              # Wait before attending a retry
              echo "::notice ::Wait ${retryWait}s before retrying command"
              sleep $retryWait

              echo "::notice ::Retry command for the $(($currentRetry + 1)) time(s)"
              retry $(($retries - 1)) $retryWait "$command" $(($currentRetry + 1))
            else
              # Return the exit code from the command
              return $exit_code
            fi
          }
          retry ${{ inputs.max_retries }} ${{ inputs.retry_wait }} "${{ inputs.command }}"
      shell: bash
