name: 'Retry Command'
description: 'Retry a simple command'
inputs:
  command:
    description: 'Command to run'
    required: true
  max_retries:
    description: 'Maximum number of attends to retry the command. Default 3'
    default: 3
    required: false
  retry_wait:
    description: 'Number of seconds to wait between retry attends. Default 5 seconds'
    default: 5
    required: false
runs:
  using: "composite"
  steps:
    - name: Run command
      run: |
          retry() {
            local retries="$1"
            local retryWait="$2"
            local command="$3"
          
            # Run the command and keep the exit code
            $command
            local exit_code=$?
          
            # If the exit code is a non-zero value (i.e. command failed), and we have not
            # reached the maximum number of retries, run the command again
            if [[ $exit_code -ne 0 && $retries -gt 0 ]]; then
              # Wait before attending a retry
              sleep $retryWait
          
              retry $(($retries - 1)) $retryWait "$command"
            else
              # Return the exit code from the command
              return $exit_code
            fi
          }
          retry ${{ inputs.max_retries }} ${{ inputs.retry_wait }}s "${{ inputs.command }}"
      shell: bash
