on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command'
        type: string
        required: true

jobs:
  windows:
    name: Build and Publish Windows Installer

    runs-on: ubuntu-latest

    steps:
      - name: Run command
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_wait_seconds: 2
          shell: bash
          command: ./gradlew check
